import { sql } from "drizzle-orm";
import { integer, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

const now = sql`CURRENT_TIMESTAMP`;

export const categories = sqliteTable("categories", {
  id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), slug: text("slug").notNull(), parentId: integer("parent_id"), description: text("description").notNull().default(""), bannerMediaId: integer("banner_media_id"), navigationVisible: integer("navigation_visible", { mode: "boolean" }).notNull().default(true), sortOrder: integer("sort_order").notNull().default(0), seoTitle: text("seo_title").notNull().default(""), metaDescription: text("meta_description").notNull().default(""), createdAt: text("created_at").notNull().default(now), updatedAt: text("updated_at").notNull().default(now)
}, (t) => [uniqueIndex("idx_categories_slug").on(t.slug), index("idx_categories_parent_sort").on(t.parentId, t.sortOrder)]);
export const products = sqliteTable("products", {
  id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), slug: text("slug").notNull(), model: text("model").notNull().default(""), sku: text("sku").notNull().default(""), status: text("status", { enum: ["draft", "published", "archived"] }).notNull().default("draft"), summary: text("summary").notNull().default(""), description: text("description").notNull().default(""), priceLabel: text("price_label").notNull().default("Contact for quote"), moq: text("moq").notNull().default(""), customization: text("customization").notNull().default(""), seoTitle: text("seo_title").notNull().default(""), metaDescription: text("meta_description").notNull().default(""), indexable: integer("indexable", { mode: "boolean" }).notNull().default(false), coverMediaId: integer("cover_media_id"), createdAt: text("created_at").notNull().default(now), updatedAt: text("updated_at").notNull().default(now)
}, (t) => [uniqueIndex("idx_products_slug").on(t.slug), index("idx_products_status_updated").on(t.status, t.updatedAt)]);
export const productCategories = sqliteTable("product_categories", { productId: integer("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), categoryId: integer("category_id").notNull().references(() => categories.id, { onDelete: "cascade" }) }, (t) => [uniqueIndex("idx_product_categories_pair").on(t.productId, t.categoryId), index("idx_product_categories_category").on(t.categoryId)]);
export const productSpecifications = sqliteTable("product_specifications", { id: integer("id").primaryKey({ autoIncrement: true }), productId: integer("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), label: text("label").notNull(), value: text("value").notNull(), sortOrder: integer("sort_order").notNull().default(0) }, (t) => [index("idx_product_specs_product_sort").on(t.productId, t.sortOrder)]);
export const media = sqliteTable("media", { id: integer("id").primaryKey({ autoIncrement: true }), key: text("key").notNull(), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull(), altText: text("alt_text").notNull().default(""), createdAt: text("created_at").notNull().default(now) }, (t) => [uniqueIndex("idx_media_key").on(t.key)]);
export const productMedia = sqliteTable("product_media", { productId: integer("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), mediaId: integer("media_id").notNull().references(() => media.id, { onDelete: "cascade" }), sortOrder: integer("sort_order").notNull().default(0) }, (t) => [uniqueIndex("idx_product_media_pair").on(t.productId, t.mediaId), index("idx_product_media_product_sort").on(t.productId, t.sortOrder)]);
export const posts = sqliteTable("posts", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), slug: text("slug").notNull(), excerpt: text("excerpt").notNull().default(""), content: text("content").notNull().default(""), status: text("status", { enum: ["draft", "published"] }).notNull().default("draft"), seoTitle: text("seo_title").notNull().default(""), metaDescription: text("meta_description").notNull().default(""), publishedAt: text("published_at"), createdAt: text("created_at").notNull().default(now) }, (t) => [uniqueIndex("idx_posts_slug").on(t.slug), index("idx_posts_status_published").on(t.status, t.publishedAt)]);
export const pages = sqliteTable("pages", { id: integer("id").primaryKey({ autoIncrement: true }), title: text("title").notNull(), slug: text("slug").notNull(), content: text("content").notNull().default(""), status: text("status", { enum: ["draft", "published"] }).notNull().default("draft"), seoTitle: text("seo_title").notNull().default(""), metaDescription: text("meta_description").notNull().default(""), updatedAt: text("updated_at").notNull().default(now) }, (t) => [uniqueIndex("idx_pages_slug").on(t.slug)]);
export const inquiries = sqliteTable("inquiries", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email").notNull(), company: text("company").notNull().default(""), jobTitle: text("job_title").notNull().default(""), phone: text("phone").notNull().default(""), country: text("country").notNull().default(""), companyWebsite: text("company_website").notNull().default(""), buyerType: text("buyer_type").notNull().default(""), preferredContact: text("preferred_contact").notNull().default("email"), privacyConsentAt: text("privacy_consent_at").notNull().default(""), quantity: text("quantity").notNull().default(""), interest: text("interest").notNull().default(""), productId: integer("product_id").references(() => products.id, { onDelete: "set null" }), productName: text("product_name").notNull().default(""), message: text("message").notNull(), sourceUrl: text("source_url").notNull().default(""), trafficSource: text("traffic_source").notNull().default(""), utmSource: text("utm_source").notNull().default(""), utmMedium: text("utm_medium").notNull().default(""), utmCampaign: text("utm_campaign").notNull().default(""), status: text("status", { enum: ["new", "contacted", "quoted", "negotiating", "won", "lost", "spam"] }).notNull().default("new"), notes: text("notes").notNull().default(""), createdAt: text("created_at").notNull().default(now) }, (t) => [index("idx_inquiries_status_created").on(t.status, t.createdAt), index("idx_inquiries_product_created").on(t.productId, t.createdAt)]);
export const settings = sqliteTable("settings", { key: text("key").primaryKey(), value: text("value").notNull(), updatedAt: text("updated_at").notNull().default(now) });
export const analyticsEvents = sqliteTable("analytics_events", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), payload: text("payload").notNull().default("{}"), createdAt: text("created_at").notNull().default(now) }, (t) => [index("idx_events_name_created").on(t.name, t.createdAt)]);
export const submissionLimits = sqliteTable("submission_limits", { key: text("key").primaryKey(), count: integer("count").notNull().default(0), windowStartedAt: integer("window_started_at").notNull(), updatedAt: text("updated_at").notNull().default(now) }, (t) => [index("idx_submission_limits_window").on(t.windowStartedAt)]);
